# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: auto_non_stop_deploy

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm test
  
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clone and Connect EC2
        run: |
          echo "${{secrets.PRIVATE_EC2_KEY}}" > private_key && 
          chmod 600 private_key &&
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@13.124.107.224 '
            export NODE_OPTIONS=--max_old_space_size=2048 &&
            export NVM_DIR=~/.nvm &&
            source ~/.nvm/nvm.sh &&
            cd wetube-clone &&
            pm2 stop init &&
            git pull origin main &&
            npm run build &&
            pm2 start init &&
            pm2 save
          '
