name: CD

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.RSPI_KEY }}

      # - run: touch private_key && chmod 600 private_key
      # - run: echo ${{secrets.EC2_PEM}} > private_key && cat private_key
      # - run: ssh -o StrictHostKeyChecking=no -i private_key ubuntu@13.124.107.224 
      #     cd ahtata-back &&
      #     git pull origin main &&
      #     sudo sh deploy.sh
      #     
