name: CI TEST

on:
  push:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Find changed test files
        id: change
        uses: dorny/paths-filter@v2
        with:
          filters: |
            src:
              - 'src/**/*.spec.ts'
      - run: echo ${{ steps.change.outputs.src }}
      - run: echo ${{ toJSON(steps.change.outputs) }}
      #- run: npm ci
      #- run: npm test -- --findRelatedTests ${{ steps.find_changed_files.outputs.paths }}
